# Build container for deployment on cloud run
substitutions:
  _REGION: "us-east1"
  _SERVICE_ACCOUNT: "api-preprocessor@contrails-301217.iam.gserviceaccount.com"
  _MAX_INSTANCES: "1000"
  _MIN_INSTANCES: "1"
  _CPU: "2"
  _MEMORY: "8Gi"

options:
  logging: "CLOUD_LOGGING_ONLY"
  machineType: "E2_HIGHCPU_8"

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--network"
      - "cloudbuild"
      - "--file"
      - "Dockerfile"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}:${_TAG}"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}:latest"
      - "."

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}"
      - "--all-tags"

  # Prune old container images
  # Keep everything for the last 30 days, then keep 10 images beyond that.
  - name: "us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest"
    waitFor:
      - "-" # Run immediately when build starts
    args:
      - "-repo"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}"
      - "-keep"
      - "10"
      - "-grace"
      - "720h"
      - "-tag-filter-any"
      - ".*"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - ${_IMAGE}
      - "--port"
      - "8080"
      - "--service-account"
      - ${_SERVICE_ACCOUNT}
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}:${_TAG}"
      - "--region"
      - ${_REGION}
      - "--timeout"
      - "600s"
      - "--cpu"
      - ${_CPU}
      - "--memory"
      - ${_MEMORY}
      - "--min-instances"
      - ${_MIN_INSTANCES}
      - "--max-instances"
      - ${_MAX_INSTANCES}
      - "--concurrency"
      - "1"
      - "--no-allow-unauthenticated"
      - "--use-http2" # https://cloud.google.com/run/docs/configuring/http2#command-line
      - "--execution-environment" # https://cloud.google.com/run/docs/about-execution-environments"
      - "gen2" # options: gen1, gen2
      - "--cpu-boost" # https://cloud.google.com/run/docs/configuring/cpu#startup-boost
      - "--set-env-vars"
      - "SINK_PATH=${_SINK_PATH},LOG_LEVEL=${_LOG_LEVEL},API_PREPROCESSOR_SUBSCRIPTION_ID=${_API_PREPROCESSOR_SUBSCRIPTION_ID}"

# Set timeout for the whole build / push at 60 minutes.
timeout: 3600s
