# Build container for deployment on cloud run
substitutions:
  _REGION: "us-east1"
  _SERVICE_ACCOUNT: "api-preprocessor@contrails-301217.iam.gserviceaccount.com"

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--network"
      - "cloudbuild"
      - "--file"
      - "Dockerfile"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}:${_TAG}"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}:latest"
      - "."

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/api-preprocessor/${_IMAGE}"
      - "--all-tags"
