apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-preprocessor
  labels:
    app: api-preprocessor
spec:
  replicas: 40
  selector:
    matchLabels:
      app: api-preprocessor
  template:
    metadata:
      labels:
        app: api-preprocessor
    spec:
      serviceAccountName: api-preprocessor-k8s-default-sa
      containers:
      - name: api-preprocessor
        image: {{ .Values.image | required ".Values.image is required" | quote }}
        env:
          - name: SOURCE_PATH
            value: {{ .Values.sourcePath | required ".Values.sourcePath is required" | quote }}
          - name: SINK_PATH
            value: {{ .Values.sinkPath | required ".Values.sinkPath is required" | quote }}
          - name: API_PREPROCESSOR_SUBSCRIPTION_ID
            value: {{ .Values.apiPreprocessorSubscriptionId | required ".Values.apiPreprocessorSubscriptionId is required" | quote }}
          - name: LOG_LEVEL
            value: INFO
        resources:
          limits:
            cpu: "1.8"
            ephemeral-storage: "1Gi"
            memory: "3200Mi"
          requests:
            cpu: "1.8"
            ephemeral-storage: "1Gi"
            memory: "3200Mi"
