apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-preprocessor
  labels:
    app: api-preprocessor
spec:
  schedule: "0 3,9,15,21 * * *"
  timeZone: "Etc/UTC"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      activeDeadlineSeconds: 5400  # 1.5 hrs
      completions: 5  # MUST MATCH VALUE FROM parallelism
      parallelism: 5  # MUST MATCH VALUE FROM completions
      backoffLimit: 10
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: api-preprocessor-k8s-default-sa
          # terminationGracePeriodSeconds should be greater than the time to
          # perform a single job iteration. When a SIGTERM is received, the job
          # has this much time to gracefully exit before being killed.
          terminationGracePeriodSeconds: 1800
          containers:
            - name: api-preprocessor
              image: {{ .Values.image | required ".Values.image is required" | quote }}
              env:
                - name: SOURCE_PATH
                  value: {{ .Values.sourcePath | required ".Values.sourcePath is required" | quote }}
                - name: SINK_PATH
                  value: {{ .Values.sinkPath | required ".Values.sinkPath is required" | quote }}
                - name: API_PREPROCESSOR_SUBSCRIPTION_ID
                  value: {{ .Values.apiPreprocessorSubscriptionId | required ".Values.apiPreprocessorSubscriptionId is required" | quote }}
                - name: LOG_LEVEL
                  value: INFO
              resources:
                requests:
                  cpu: "2"
                  memory: "5000Mi"
                limits:
                  cpu: "2"
                  memory: "5000Mi"
