resource "google_bigquery_dataset" "api_preprocessor_dev" {
  dataset_id = "api_preprocessor_dev"
  friendly_name = "[DEV] api preprocessor"
  description = "data assets generated by the api preprocessor"
  location = "US"
  delete_contents_on_destroy = false
}

resource "google_bigquery_table" "cocip_regions_dev" {
  dataset_id = google_bigquery_dataset.api_preprocessor_dev.dataset_id
  table_id   = "cocip_regions_dev"
  friendly_name = "[DEV] cocip regions"
  description = "region polygons generated from CoCip"
  deletion_protection = true
  time_partitioning {
    field = "timestamp"
    type = "WEEK"
  }
  schema = file("${path.module}/schemas/cocip_regions.json")
}
